Testovoe zadaniye/Models/AddTour.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Testovoe_zadaniye.Models
{
    public class AddTour
    {
        [Required]
        [StringLength(60, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        public string Name { get; set; }


        //[DataRange (DateTime.Now, DateTime.Now.AddYears(1))]
        public DateTime Date { get; set; }
    }

    public class DataRangeAttribute : ValidationAttribute
    {
        private DateTime _beginDate;
        private DateTime _endDate;
        public DataRangeAttribute(DateTime begin, DateTime end)
        {
            _beginDate = begin;
            _endDate = end;
        }

        public override bool IsValid(object value)
        {
            DateTime dateToValidate;
            DateTime.TryParse(value.ToString(), out dateToValidate);

            // сделать проверку что дата корректна итп 

            return dateToValidate > _beginDate && dateToValidate < _endDate;
        }

        public override string FormatErrorMessage(string name)
        {
            return String.Format(
                "В указанном поле {0} введена не правильная дата , введите дату в диапозоне {1} - {2}", name, _beginDate,
                _endDate);
        }
    }
}

Testovoe zadaniye/Controllers/AddTourController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Testovoe_zadaniye.DataBase;
using Testovoe_zadaniye.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Runtime.CompilerServices;
using Testovoe_zadaniye.LoggingMechanism;
using Testovoe_zadaniye.FileUploading;
using Microsoft.AspNetCore.Authorization;

namespace Testovoe_zadaniye.Controllers
{
    public class AddTourController : Controller
    {
        TouragencyContext db;
        IWebHostEnvironment _appEnvironment;
        Logger logger;

        public AddTourController(TouragencyContext context, IWebHostEnvironment appEnvironment)
        {
            db = context;
            LoggerCreator loggerCreator = new TxtLoggerCreator();
            logger = loggerCreator.FactoryMethod();
            _appEnvironment = appEnvironment;

        }

        [Authorize]
        public IActionResult ToTourAdd()
        {
            AddTour model = new AddTour();

            return View(model);
        }
        [Authorize]
        [HttpPost]
        public IActionResult ToTourAdd(AddTour addTour)
        {

            Tour tour = new Tour();
            tour.Name = addTour.Name;
            tour.Data = addTour.Date;
            if (tour.Name != null && tour.Data != null)
            {
            db.Tours.Add(tour);
            db.SaveChanges();
            }
            else
            {
                throw new Exception("Some field of tour is null");
            }


            string message = "Add of new Tour";
            logger.LoggMessage(this.GetType().Name, message);

            return RedirectToAction("GuideToToursAcces", "Navigation");
        }
        [Authorize]
        public ActionResult ToTourEdit(int id = 0)
        {
            Tour tour = new Tour();
            if (id != 0)
            {
                tour = db.Tours.Where(x => x.TourId == id).FirstOrDefault();
            }
            EditTourForm model = new EditTourForm();
            model.Date = tour.Data;
            model.Name = tour.Name;
            model.TourId = tour.TourId;


            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ToTourEdit(EditTourForm model)
        {
            Tour tour = new Tour();
            tour.Data = model.Date;
            tour.Name = model.Name;
            tour.TourId = model.TourId;

            if (model.TourId != 0)
            {
                db.Entry(tour).State = EntityState.Modified;
                db.SaveChanges();
            }
            string message = "Edit of chosen Tour";
            logger.LoggMessage(this.GetType().Name, message);

            return Ok();
        }
    }
}

Testovoe zadaniye/Views/AddTour/ToTourAdd.cshtml
@model Testovoe_zadaniye.Models.AddTour

    <img class="mb-4" src="~/images/logo.png" alt="" width="100" height="100">

    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h3>Please enter new tour</h3>
        </div>
    </div>

@using (Html.BeginForm("ToTourAdd", "AddTour", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row justify-content-md-center">
        <div class="col-md-3 mb-3">
            @Html.LabelFor(c => c.Name)
            @Html.TextBoxFor(c => c.Name, new { @class = "form-control", @required = "" })
            @Html.ValidationMessageFor(c => c.Name ,"", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-md-2">
            <a class="btn btn-primary btn-lg" href="javascript: history.go(-1)" role="button">Previous Page</a>
        </div>
        <div class="col-md-2">

            <button class="btn btn-primary btn-lg btn-block" type="submit">Confirm</button>
        </div>
    </div>
}

Testovoe zadaniye/Views/AddTour/ToTourEdit.cshtml
@model Testovoe_zadaniye.Models.EditTourForm

<img class="mb-4" src="~/images/logo.png" alt="" width="100" height="100">

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <h3>Enter tour changes</h3>
    </div>
</div>

@using (Html.BeginForm("ToTourEdit", "AddTour", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    onSubmit = "return jQueryAjaxPost(this);",
    data_restUrl = Url.Action("ToTourEdit", "AddTour", new { id = 0 }),
    id = "jqSubmit"
}))

{
    @Html.HiddenFor(c => c.TourId)

    <div class="row justify-content-md-center">
        <div class="col-md-3 mb-3">
            @Html.LabelFor(c => c.Name)
            @Html.TextBoxFor(c => c.Name, new { @class = "form-control", @required = "" })
            @Html.ValidationMessageFor(model => model.Name ,"", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

        <a class="btn btn-primary btn-lg" href="javascript: history.go(-1)" role="button">Previous Page</a>
        <div class="spinner-border" id="spinner"></div>
     
}

<script>

    $('#spinner').hide();
    var debounceTimer = null;
    var eventHandler = function () {

        clearTimeout(debounceTimer);
            $('#spinner').show();
        debounceTimer = setTimeout(function () {
            $('#jqSubmit').submit();
            console.log("The field has been changed.");
            $('#spinner').hide();
        }, 2000);
    }
    $(document).ready(function () {
        $("#Name").keyup(eventHandler);
        //$("#GuideId, #checkDiv input, #Age").click(eventHandler);
        $("#Date").change(eventHandler);
    });


</script>