Testovoe zadaniye/Models/AddTour.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Testovoe_zadaniye.Models
{
    public class AddTour
    {
        [Required]
        [StringLength(60, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        public string Name { get; set; }


        //[DataRange (DateTime.Now, DateTime.Now.AddYears(1))]
        public DateTime Date { get; set; }
    }

    public class DataRangeAttribute : ValidationAttribute
    {
        private DateTime _beginDate;
        private DateTime _endDate;
        public DataRangeAttribute(DateTime begin, DateTime end)
        {
            _beginDate = begin;
            _endDate = end;
        }

        public override bool IsValid(object value)
        {
            DateTime dateToValidate;
            DateTime.TryParse(value.ToString(), out dateToValidate);

            // сделать проверку что дата корректна итп 

            return dateToValidate > _beginDate && dateToValidate < _endDate;
        }

        public override string FormatErrorMessage(string name)
        {
            return String.Format(
                "В указанном поле {0} введена не правильная дата , введите дату в диапозоне {1} - {2}", name, _beginDate,
                _endDate);
        }
    }
}

Testovoe zadaniye/Models/EditTourForm.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace Testovoe_zadaniye.Models
{
    public class EditTourForm
    {
        public int TourId { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$", ErrorMessage = "Only numbers and alphabets allowed, capital letter is compulsory, symbols only allow '-'")]
        public string Name { get; set; }
        public DateTime Date { get; set; }
    }
}

Testovoe zadaniye/Models/Entities/Tour.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Testovoe_zadaniye.Models.Entities
{
    public class Tour
    {
        [Key]
        //id экскурсии
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TourId { get; set; }
        // Название экскурсии
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(30)]
        [Required]
        public string Name { get; set; }
        // Пароль Гида
        [DataType(DataType.Date)]
        public DateTime Data { get; set; }
        public ICollection<TouristTour> TouristTours { get; set; }
        [NotMapped]
        public bool selected { get; set; }

    }
}

Testovoe zadaniye/Controllers/AddTourController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Testovoe_zadaniye.DataBase;
using Testovoe_zadaniye.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.Runtime.CompilerServices;
using Testovoe_zadaniye.LoggingMechanism;
using Testovoe_zadaniye.FileUploading;
using Microsoft.AspNetCore.Authorization;

namespace Testovoe_zadaniye.Controllers
{
    public class AddTourController : Controller
    {
        TouragencyContext db;
        IWebHostEnvironment _appEnvironment;
        Logger logger;

        public AddTourController(TouragencyContext context, IWebHostEnvironment appEnvironment)
        {
            db = context;
            LoggerCreator loggerCreator = new TxtLoggerCreator();
            logger = loggerCreator.FactoryMethod();
            _appEnvironment = appEnvironment;

        }

        [Authorize]
        public IActionResult ToTourAdd()
        {
            AddTour model = new AddTour();

            return View(model);
        }
        [Authorize]
        [HttpPost]
        public IActionResult ToTourAdd(AddTour addTour)
        {

            Tour tour = new Tour();
            tour.Name = addTour.Name;
            tour.Data = addTour.Date;
            if (tour.Name != null && tour.Data != null)
            {
            db.Tours.Add(tour);
            db.SaveChanges();
            }
            else
            {
                throw new Exception("Some field of tour is null");
            }


            string message = "Add of new Tour";
            logger.LoggMessage(this.GetType().Name, message);

            return RedirectToAction("GuideToToursAcces", "Navigation");
        }
        [Authorize]
        public ActionResult ToTourEdit(int id = 0)
        {
            Tour tour = new Tour();
            if (id != 0)
            {
                tour = db.Tours.Where(x => x.TourId == id).FirstOrDefault();
            }
            EditTourForm model = new EditTourForm();
            model.Date = tour.Data;
            model.Name = tour.Name;
            model.TourId = tour.TourId;


            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ToTourEdit(EditTourForm model)
        {
            Tour tour = new Tour();
            tour.Data = model.Date;
            tour.Name = model.Name;
            tour.TourId = model.TourId;

            if (model.TourId != 0)
            {
                db.Entry(tour).State = EntityState.Modified;
                db.SaveChanges();
            }
            string message = "Edit of chosen Tour";
            logger.LoggMessage(this.GetType().Name, message);

            return Ok();
        }
    }
}

Testovoe zadaniye/Controllers/TourController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Testovoe_zadaniye.Models;
using Microsoft.AspNetCore.Authorization;
using Testovoe_zadaniye.AppServices.Interfaces;
using Testovoe_zadaniye.Models.OperationModels;

namespace Testovoe_zadaniye.Controllers
{
    public class TourController : Controller
    {

        ILoggerCreator _loggerCreator;
        ITourService _tourService;

        public TourController(ITourService tourService, ILoggerCreator loggerCreator)
        {
            _loggerCreator = loggerCreator;
            _tourService = tourService;
        }

        [Authorize]
        public IActionResult AddTour()
        {
            var result =_tourService.CreateNewTourForm();
            return View(result);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddTour(NewTourForm addTour)
        {
            await _tourService.SaveNewTour(addTour);

            string message = "Add of new Tour";
            var logger = _loggerCreator.FactoryMethod();
            logger.LoggMessage(this.GetType().Name, message);

            return RedirectToAction("AllToursForGuide", "Guide");
        }

        [Authorize]
        public ActionResult EditTour(int id = 0)
        {
            var result = _tourService.CreateEditTourForm(id);
            return View(result);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditTour(TourEditForm model)
        {
            _tourService.SaveEditedTour(model);

            string message = "Edit of chosen Tour";
            var logger = _loggerCreator.FactoryMethod();
            logger.LoggMessage(this.GetType().Name, message);

            return Ok();
        }

        public async Task<IActionResult> ToursOfTourist(int? id)
        {
            string message = "Display tours";
            var logger = _loggerCreator.FactoryMethod();
            logger.LoggMessage(this.GetType().Name, message);

            //SQL useful realisation
            //var tours = db.Tours.FromSqlRaw("sp_ShowToursFromTT @TouristId={0}", id).ToList();
            //return View(tours);

            var tours = await _tourService.ToursOfChosenTourist(id);

            return View(tours);
        }

        [HttpGet]
        [ActionName("DeleteTour")]
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> DeleteTour(int? id)
        {
            if (id != null)
            {
                string message = "Deleting of Tour";
                var logger = _loggerCreator.FactoryMethod();
                logger.LoggMessage(this.GetType().Name, message);

                await _tourService.DeleteChosenTour(id);
                return RedirectToAction("AllToursForGuide", "Guide");
            }

            string message1 = "Unsucessful tour delete";
            var logger1 = _loggerCreator.FactoryMethod();
            logger1.LoggMessage(this.GetType().Name, message1);

            return NotFound();
        }

        public async Task<IActionResult> AllToursList()
        {

            string message = "Display tours List";
            var logger = _loggerCreator.FactoryMethod();
            logger.LoggMessage(this.GetType().Name, message);

            var result = await _tourService.ShowAllTours();

            return View(result);
        }
    }
}

Testovoe zadaniye/Views/Tour/AddTour.cshtml
@model Testovoe_zadaniye.Models.OperationModels.NewTourForm

    <img class="mb-4" src="~/images/logo.png" alt="" width="100" height="100">

    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h3>Please enter new tour</h3>
        </div>
    </div>

@using (Html.BeginForm("AddTour", "Tour", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row justify-content-md-center">
        <div class="col-md-3 mb-3">
            @Html.LabelFor(c => c.Name)
            @Html.TextBoxFor(c => c.Name, new { @class = "form-control", @required = "" })
            @Html.ValidationMessageFor(c => c.Name ,"", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-md-2">
            <a class="btn btn-primary btn-lg" href="javascript: history.go(-1)" role="button">Previous Page</a>
        </div>
        <div class="col-md-2">

            <button class="btn btn-primary btn-lg btn-block" type="submit">Confirm</button>
        </div>
    </div>
}

Testovoe zadaniye/Views/Tour/AllToursList.cshtml
@model IEnumerable<Testovoe_zadaniye.Models.Entities.Tour>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<img class="mb-4" src="~/images/logo.png" alt="" width="100" height="100">

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <p><h1>Tour list</h1></p>
    </div>
</div>

<div class="row justify-content-md-center">
    @foreach (var tour in Model)
    {
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 shadow-sm">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">@tour.Name</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">@tour.Data </h1>
                </div>
            </div>
        </div>
    }
</div>

<div class="row justify-content-md-center">
    <div class="col-md-3">
        <input class="btn btn-primary btn-lg" type="button" value="Click to Display Map" onclick="DisplayGoogleMap()" />
    </div>
    <div class="col-md-2">
        <a class="btn btn-primary btn-lg" href="javascript: history.go(-1)" role="button">Previous Page</a>
    </div>
</div>

<p><center><div id="myDiv" style="width:800px;height:600px;"></div></center></p>

    <script src="https://maps.googleapis.com/maps/api/js?"></script>
    <script type="text/javascript">
        function DisplayGoogleMap() {

            //Set the Latitude and Longitude of the Map
            var myAddress = new google.maps.LatLng(41.3877306, 2.1626061);

            // Section of tours
            //
            var TourOne = new google.maps.LatLng(41.404641, 2.174969);
            //
            var TourTwo = new google.maps.LatLng(41.391798, 2.164656);
            //
            var TourThree = new google.maps.LatLng(41.368319, 2.154031);
            //
            var TourFour = new google.maps.LatLng(41.380574, 2.122917);
            //
            var TourFive = new google.maps.LatLng(41.422757, 2.119255);
            //
            var TourSix = new google.maps.LatLng(41.639508, 2.713662);
            //
            var TourSeven = new google.maps.LatLng(41.363846, 2.167728);
            //
            var TourEight = new google.maps.LatLng(41.385321, 2.180710);
            //
            var TourNine = new google.maps.LatLng(41.613967, 2.654539);
            //
            var TourTen = new google.maps.LatLng(41.375696, 2.177621);
            //
            var TourEleven = new google.maps.LatLng(41.414397, 2.153142);


            //Create Options or set different Characteristics of Google Map
            var mapOptions = {
                center: myAddress,
                zoom: 10,
                minZoom: 10,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            //Display the Google map in the div control with the defined Options
            var map = new google.maps.Map(document.getElementById("myDiv"), mapOptions);



            var marker = new google.maps.Marker({
                position: myAddress,
                map: map,
                animation: google.maps.Animation.BOUNCE,

            });

            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/red-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourOne,
                map: map
            });

            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourTwo,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourThree,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')
            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourFour,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourFive,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourSix,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourSeven,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')
            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourEight,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourNine,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourTen,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')

            //Set Marker on the Map
            var marker = new google.maps.Marker({
                position: TourEleven,
                map: map
            });
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')



            marker.setMap(map);
        }
    </script>

Testovoe zadaniye/Views/Tour/EditTour.cshtml
@model Testovoe_zadaniye.Models.OperationModels.TourEditForm

<img class="mb-4" src="~/images/logo.png" alt="" width="100" height="100">

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <h3>Enter tour changes</h3>
    </div>
</div>

@using (Html.BeginForm("EditTour", "Tour", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    onSubmit = "return jQueryAjaxPost(this);",
    data_restUrl = Url.Action("EditTour", "Tour", new { id = 0 }),
    id = "jqSubmit"
}))

{
    @Html.HiddenFor(c => c.TourId)

    <div class="row justify-content-md-center">
        <div class="col-md-3 mb-3">
            @Html.LabelFor(c => c.Name)
            @Html.TextBoxFor(c => c.Name, new { @class = "form-control", @required = "" })
            @Html.ValidationMessageFor(model => model.Name ,"", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

        <a class="btn btn-primary btn-lg" href="javascript: history.go(-1)" role="button">Previous Page</a>
        <div class="spinner-border" id="spinner"></div>
     
}

<script>

    $('#spinner').hide();
    var debounceTimer = null;
    var eventHandler = function () {

        clearTimeout(debounceTimer);
            $('#spinner').show();
        debounceTimer = setTimeout(function () {
            $('#jqSubmit').submit();
            console.log("The field has been changed.");
            $('#spinner').hide();
        }, 2000);
    }
    $(document).ready(function () {
        $("#Name").keyup(eventHandler);
        //$("#GuideId, #checkDiv input, #Age").click(eventHandler);
        $("#Date").change(eventHandler);
    });


</script>

Testovoe zadaniye/Views/Tour/ToursOfTourist.cshtml
@model IEnumerable<Testovoe_zadaniye.Models.Entities.Tour>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<img class="mb-4" src="~/images/logo.png" alt="" width="100" height="100">

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <p><h1>Tours list</h1></p>
    </div>
</div>

<div class="row justify-content-md-center">
    @foreach (var tour in Model)
    {
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 shadow-sm">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">@tour.Name</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">@tour.Data </h1>
                </div>
            </div>
        </div>
    }
</div>

<a class="btn btn-primary btn-lg" href="javascript: history.go(-1)" role="button">Previous Page</a>